pull_request_rules:
  - name: automatic merge on CI success and review
    conditions:
      - status-success=Community-TC (pull_request)
      - "#approved-reviews-by>=1"
    actions:
        merge:
            strict: true
            method: rebase